# Generated by Django 2.1.2 on 2019-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveDB', '0003_auto_20190215_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_hum_tem',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
