# Generated by Django 2.1.2 on 2019-02-15 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saveDB', '0004_auto_20190215_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_hum_tem',
            old_name='title',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='time_hum_tem',
            name='body',
        ),
        migrations.AddField(
            model_name='time_hum_tem',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
