# Generated by Django 2.1.7 on 2019-04-24 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saveDB', '0005_auto_20190215_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_hum_tem',
            name='message',
        ),
        migrations.RemoveField(
            model_name='time_hum_tem',
            name='topic',
        ),
        migrations.AddField(
            model_name='time_hum_tem',
            name='DATA_MQTT',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
