# Generated by Django 2.1.7 on 2019-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveDB', '0006_auto_20190424_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_hum_tem',
            name='DATA_MQTT',
            field=models.CharField(max_length=500),
        ),
    ]
