# Generated by Django 2.1.7 on 2019-07-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_status_3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceNode2status',
            new_name='Device3Node2status',
        ),
        migrations.RenameField(
            model_name='device3node2status',
            old_name='Device_Node2_Status',
            new_name='Device_3_Node2_Status',
        ),
    ]
